import React from 'react';
import { View, Text, StyleSheet, useColorScheme } from 'react-native';

interface DisclaimerProps {
  style?: any;
}

const Disclaimer: React.FC<DisclaimerProps> = ({ style }) => {
  const colorScheme = useColorScheme();
  const isDark = colorScheme === 'dark';
  
  return (
    <View style={[styles.disclaimerContainer, isDark && styles.darkDisclaimerContainer, style]}>
      <Text style={[styles.disclaimerText, isDark && { color: '#AAAAAA' }]}>
        <Text style={styles.disclaimerBold}>Disclaimer:</Text> This app is for educational purposes only. All analysis, suggestions, and content are generated by AI models and should not be considered as financial advice. Past performance is not indicative of future results. Always conduct your own research and consult with qualified financial professionals before making investment decisions. The app's AI models may have limitations and may not account for all market factors or recent developments. Users are solely responsible for their investment decisions and should understand that all investments involve risk.
      </Text>
    </View>
  );
};

const styles = StyleSheet.create({
  disclaimerContainer: {
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    padding: 12,
    marginHorizontal: 16,
    marginVertical: 16,
    borderRadius: 8,
  },
  darkDisclaimerContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  disclaimerText: {
    fontSize: 12,
    color: '#666666',
    lineHeight: 18,
  },
  disclaimerBold: {
    fontWeight: 'bold',
  },
});

export default Disclaimer; 