import React from 'react';
import { View, Text, StyleSheet, useColorScheme } from 'react-native';

interface DisclaimerProps {
  style?: any;
}

const Disclaimer: React.FC<DisclaimerProps> = ({ style }) => {
  const colorScheme = useColorScheme();
  const isDark = colorScheme === 'dark';
  
  return (
    <View style={[styles.disclaimerContainer, isDark && styles.darkDisclaimerContainer, style]}>
      <Text style={[styles.disclaimerText, isDark && { color: '#AAAAAA' }]}>
        <Text style={styles.disclaimerBold}>Disclaimer:</Text> Analysis is for educational purposes only,
        intended for people to learn more about finance, but not giving financial advice.
        All suggestions are generated by AI models.
      </Text>
    </View>
  );
};

const styles = StyleSheet.create({
  disclaimerContainer: {
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    padding: 12,
    marginHorizontal: 16,
    marginVertical: 16,
    borderRadius: 8,
  },
  darkDisclaimerContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  disclaimerText: {
    fontSize: 12,
    color: '#666666',
    lineHeight: 18,
  },
  disclaimerBold: {
    fontWeight: 'bold',
  },
});

export default Disclaimer; 